server:
  port: 9080
  servlet:
    context-path: /UserManagement
spring:
  datasource:
    driver-class-name: org.h2.Driver
    password: 
    url: jdbc:h2:mem:testdb
    username: sa

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    defer-datasource-initialization: true
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
# these below smtp properties for sending the mail from spring boot app
  mail:
    host: smtp.gmail.com
    port: 587
    username: pprem6672@gmail.com
    password: czbwryagnnwrrilf    
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  
